# file: dev.yaml
#
# Development server configuration. Most useful when a dev needs to run from an IDE or local shell rather than a Docker
# container or Kubernetes cluster.
#

terraform:
  executable: "/bin/terraform"

workspace:
  path: "./hack/workspace"

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  appenders:
    - type: console